/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lags.view;

import java.sql.Date;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lags.dao.KhuyenMaiDao;
import lags.entity.KhuyenMai;
import lags.util.XDialog;

/**
 *
 * @author ADMIN
 */
public final class GiamGiaform extends javax.swing.JPanel {

    /**
     * Creates new form GiamGiaform
     */
    KhuyenMaiDao daoKM = new KhuyenMaiDao();
    List<KhuyenMai> listKM = List.of();

    public GiamGiaform() {
        initComponents();
        this.fillTable();
        this.loadLoaiGiam();
        this.loadTrangThai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idKhuyenmai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_loaiGiam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_GiaTriGiam = new javax.swing.JTextField();
        txt_GiamMax = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DkApDung = new javax.swing.JTextArea();
        cbo_TrangThai = new javax.swing.JComboBox<>();
        txt_NgayTao = new javax.swing.JTextField();
        txt_NgayHetHan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KhuyenMai = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý khuyến mãi");

        jLabel2.setText("ID khuyến mãi:");

        txt_idKhuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idKhuyenmaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Loại giảm:");

        cbo_loaiGiam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Giá trị giảm:");

        jLabel5.setText("Giảm tối đa:");

        jLabel6.setText("Điều kiện áp dụng:");

        jLabel7.setText("Trạng thái:");

        jLabel8.setText("Ngày tạo:");

        jLabel9.setText("Ngày hết hạn:");

        txt_DkApDung.setColumns(20);
        txt_DkApDung.setRows(5);
        jScrollPane1.setViewportView(txt_DkApDung);

        cbo_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_NgayHetHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayHetHanActionPerformed(evt);
            }
        });

        tbl_KhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idKhuyenMai", "Loại Giảm", "Giá trị giảm", "Giảm tối đa", "Điều kiện áp dụng", "Trạng thái", "Ngày tạo ", "Ngày hết hạn"
            }
        ));
        tbl_KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_KhuyenMai);

        btn_Add.setText("Thêm");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Del.setText("Xóa");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_GiamMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(cbo_loaiGiam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_idKhuyenmai, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_GiaTriGiam, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbo_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_NgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(txt_NgayHetHan)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel1)))
                        .addGap(0, 254, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbo_loaiGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txt_NgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_GiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_NgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_GiamMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Add)
                            .addComponent(btn_Sua)
                            .addComponent(btn_Del)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKhuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idKhuyenmaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idKhuyenmaiActionPerformed

    private void txt_NgayHetHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayHetHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayHetHanActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        this.create();
        this.fillTable();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void tbl_KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhuyenMaiMouseClicked
        // TODO add your handling code here:
        int row = tbl_KhuyenMai.getSelectedRow();
        this.setForm(row);
        this.fillTable();
    }//GEN-LAST:event_tbl_KhuyenMaiMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        this.update();
        this.fillTable();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        // TODO add your handling code here:
        this.delete();
        this.fillTable();
    }//GEN-LAST:event_btn_DelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JComboBox<String> cbo_TrangThai;
    private javax.swing.JComboBox<String> cbo_loaiGiam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_KhuyenMai;
    private javax.swing.JTextArea txt_DkApDung;
    private javax.swing.JTextField txt_GiaTriGiam;
    private javax.swing.JTextField txt_GiamMax;
    private javax.swing.JTextField txt_NgayHetHan;
    private javax.swing.JTextField txt_NgayTao;
    private javax.swing.JTextField txt_idKhuyenmai;
    // End of variables declaration//GEN-END:variables

    public void loadLoaiGiam() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("1 - Giảm %");
        model.addElement("2 - Giảm số tiền");
        cbo_loaiGiam.setModel(model);

        // Tùy chọn: chọn mặc định giá trị đầu tiên
        cbo_loaiGiam.setSelectedIndex(0);
    }

    public void loadTrangThai() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("0 - Ngừng áp dụng");
        model.addElement("1 - Đang áp dụng");
        cbo_TrangThai.setModel(model);

        // Tùy chọn: chọn mặc định giá trị đầu tiên
        cbo_TrangThai.setSelectedIndex(0);
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_KhuyenMai.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        KhuyenMaiDao dao = new KhuyenMaiDao();
        List<KhuyenMai> list = dao.findAll();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // định dạng ngày

        for (KhuyenMai km : list) {
            model.addRow(new Object[]{
                km.getIdKhuyenMai(),
                km.getLoaiGiam() == 1 ? "Phần trăm" : "Số tiền",
                km.getGiaTriGiam(),
                km.getGiamToiDa(),
                km.getDkApDung(),
                km.getTrangThai() == 1 ? "Đang áp dụng" : "Ngừng áp dụng",
                sdf.format(km.getNgayTao()),
                sdf.format(km.getNgayHetHan())
            });
        }
    }

    public void setForm(int row) {
        txt_idKhuyenmai.setText(tbl_KhuyenMai.getValueAt(row, 0).toString());

        cbo_loaiGiam.setSelectedIndex(tbl_KhuyenMai.getValueAt(row, 1).toString()=="Phần trăm"?0:1);

        txt_GiaTriGiam.setText(tbl_KhuyenMai.getValueAt(row, 2).toString());
        txt_GiamMax.setText(tbl_KhuyenMai.getValueAt(row, 3).toString());

        cbo_TrangThai.setSelectedIndex(tbl_KhuyenMai.getValueAt(row, 5).toString()=="Đang áp dụng"?1:0);

        txt_NgayTao.setText(tbl_KhuyenMai.getValueAt(row, 6).toString());
        txt_NgayHetHan.setText(tbl_KhuyenMai.getValueAt(row, 7).toString());
        txt_DkApDung.setText(tbl_KhuyenMai.getValueAt(row, 4).toString());
    }

    public KhuyenMai getForm() {
        KhuyenMai entity = new KhuyenMai();

        entity.setIdKhuyenMai(txt_idKhuyenmai.getText());

        // Lấy số ở đầu chuỗi combo box
        String loaiGiamStr = cbo_loaiGiam.getSelectedItem().toString().split(" - ")[0];
        entity.setLoaiGiam(Integer.parseInt(loaiGiamStr));

        entity.setGiaTriGiam(Integer.parseInt(txt_GiaTriGiam.getText()));
        entity.setGiamToiDa(Integer.parseInt(txt_GiamMax.getText()));
        entity.setDkApDung(txt_DkApDung.getText());

        String trangThaiStr = cbo_TrangThai.getSelectedItem().toString().split(" - ")[0];
        entity.setTrangThai(Integer.parseInt(trangThaiStr));

        // Ngày nếu có
        entity.setNgayTao(Date.valueOf(txt_NgayTao.getText()));       // yyyy-MM-dd
        entity.setNgayHetHan(Date.valueOf(txt_NgayHetHan.getText()));

        return entity;
    }

    public void create() {
        try {
            KhuyenMai entity = this.getForm();
            daoKM.create(entity);
            this.fillTable();
            JOptionPane.showMessageDialog(this, "Them thanh cong!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Them that bai!");
            e.printStackTrace(); // để dễ debug khi có lỗi
        }
    }

    public void update() {
        KhuyenMai entity = this.getForm();
        daoKM.create(entity);
        this.fillTable();
    }

    public void delete() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
            String id = txt_idKhuyenmai.getText();
            daoKM.deleteByID(id);
            this.fillTable();
        }
    }

}
